# Custom Language File for Launcher Customizer

[ejs.app]
title = "LBDS Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "https://x.com/lbds_mc"
mediaInstagramURL = "https://www.instagram.com/lebanquetdusorcier/"
mediaYouTubeURL = "https://www.youtube.com/@lebanquetdusorcier4356"
mediaDiscordURL = "https://discord.com/invite/lebanquetdusorcier"

[ejs.settings]
sourceGithubLink = "https://github.com/lebanquetdusorcier/LBDSLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur LBDS"
welcomeDescription = "Bienvenue sur Le Banquet du Sorcier.

Le banquet du sorcier est un serveur RP sur l'univers magique d'Harry Potter où tu pourras incarner ton propre personnage et vivre ta propre aventure à Poudlard.
Apprenez des sortilèges, confectionnez des potions, découvrez la faune et la flore et bien plus encore !

En bref, soyez le sorcier que vous avez toujours rêvé d'incarner !"
welcomeDescCTA = "Il ne vous reste plus qu'à nous rejoindre !"
